[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

# Handle SPA routing for Next.js static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
